extra:
  api_base_url: https://www.salt.ac.za/wm/api

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - API: api.md
  - Development: development.md
  - Implementation: implementation.md

plugins:
  - macros

site_name: SALT Web Manager

theme:
  name: material
