site_name: SALT Web Manager

nav:
  - Home: index.md
  - API: api.md
  - Development: development.md
  - Implementation: implementation.md

markdown_extensions:
  - admonition

theme:
  name: material
